config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root 'tasks#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :find_task, only: [:show, :edit, :update, :destroy]

	def index
		if params[:category].blank?
			@tasks = Task.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@tasks = Task.where(category_id: @category_id).order("created_at DESC")
		end
	end

	def show
		
	end

	def new
		@task = Task.new
	end

	def edit
		
	end

	def create
		@task = Task.new(tasks_params)

		if @task.save
			redirect_to @task
		else
			render 'new'
		end
	end

	def update
		if @task.update
			redirect_to @task
		else
			render 'edit'
		end
	end

	def destroy
		@task.destroy
		redirect_to root_path
	end

	private

		def tasks_params
			params.require(:task).permit(:title, :description, :company, :url, :category_id)
		end

		def find_task
			@task = Task.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>ChoreUp</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "ChoreUp", root_path %>
      </div>
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "All Tasks", root_path %>
        </li>
        <% Category.all.each do |category| %>
          <li>
            <%= link_to category.name, tasks_path(category: category.name) %>
          </li>
        <% end %>
      </ul>
      <%= link_to "New Task", new_task_path, class: "navbar-text navbar-right navbar-link" %>
    </div>
  </nav>
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task, html: { class: 'form-horizontal' }) do |f| %>
	<%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a category" }, input_html: { class: "dropdown-toggle" } %>
	<%= f.input :title, lable: "Task Title", input_html: { class: "form-control" } %>
	<%= f.input :description, label: "Task Description", input_html: { class: "form-control" } %>
	<%= f.input :company, label: "Your Company", input_html: { class: "form-control" } %>
	<%= f.input :url, label: "Link To Task", input_html: { class: "form-control" } %>
	<br/>
	<%= f.button :submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/tasks/index.html.erb
<div id="jobs">
  <% @tasks.each do |task| %>
    <div class="job">
      <h2>
        <%= link_to task.title, task %>
      </h2>
      <br/>
      <p>
        <%= task.company %>
      </p>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/tasks/show.html.erb
<div id="jobs">
  <div class="job">
    <h2>
      <%= @task.title %>
    </h2>
    <p>
      <%= @task.description %>
    </p>
    <p>
      <%= @task.company %>
    </p>
    <button class="btn btn-default">
      <%= link_to "Complete Task", @task.url %>
    </button>
  </div>
</div>
<div id="links">
  <%= link_to "Home", root_path, class: "btn btn-sm btn-default" %>
  <%= link_to "Edit", edit_task_path(@task), class: "btn btn-sm btn-default" %>
  <%= link_to "Delete", task_path(@task), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-default" %>
</div>